#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions    # Tutorial run functions


cleanCase
rm -r 0
rm bubbleInfo
rm -r AlphaInit

#------------------------------------------------------------------------------
