#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh -region fluid
cp -r 0.orig 0
runApplication snappyHexMesh -region fluid -overwrite
#runApplication extrudeMesh -region fluid
touch a.foam
runApplication paraview a.foam
#runApplication decomposePar -region fluid
#runParallel $(getApplication)



#------------------------------------------------------------------------------
